sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
cache:
  - apt
  - pip
install:
  - pip install -r requirements.ini
before_script:
  - python manage.py makemigrations 
  - python manage.py migrate
script:
  - coverage run --source=. --omit='*tests*,*migrations*,*admin*' -m py.test -v --tb=native
after_success:
  - coveralls
