sudo: false
language: python
python:
  - "3.6"
cache:
  - apt
  - pip
install:
  - pip install -r requirements.ini
script:
  - python3 manage.py makemigrations 
  - python3 manage.py migrate
  - coverage run --source=. --omit='*tests*,*migrations*,*admin*,*mytest*' -m py.test -v --tb=native
after_success:
  - coveralls
